name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20 for consistency with EB

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Zip the app
      - name: Zip the app
        run: zip -r app.zip . -x "*.git*"

      # Step 5: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 6: Upload app to S3
      - name: Upload app to S3
        run: |
          S3_BUCKET="ci-cd-eb-bundles"
          S3_KEY="app-${{ github.sha }}-${{ github.run_id }}.zip"
          aws s3 cp app.zip s3://$S3_BUCKET/$S3_KEY --region us-east-1

      # Step 7: Create EB application version
      - name: Create EB application version
        run: |
          EB_APP_NAME="ci-cd-app"
          VERSION_LABEL="github-${{ github.sha }}-${{ github.run_id }}"
          S3_BUCKET="ci-cd-eb-bundles"
          S3_KEY="app-${{ github.sha }}-${{ github.run_id }}.zip"
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=$S3_KEY \
            --region us-east-1

      # Step 8: Update EB environment
      - name: Update EB environment
        run: |
          EB_APP_NAME="ci-cd-app"
          EB_ENV_NAME="ci-cd-env"
          VERSION_LABEL="github-${{ github.sha }}-${{ github.run_id }}"
          aws elasticbeanstalk update-environment \
            --application-name $EB_APP_NAME \
            --environment-name $EB_ENV_NAME \
            --version-label $VERSION_LABEL \
            --region us-east-1
